#!/usr/bin/env python3
"""Self-contained GPAW Fukui function calculation for isolated molecules.

Runs 3 single-point DFT calculations (N, N+1, N-1) at fixed geometry
using GPAW with plane-wave PBE, gamma-point only. Writes:
  - All-electron density cube files (rho_N.cube, rho_A.cube, rho_C.cube)
  - Fukui function cube files (fukui_f_plus.cube, fukui_f_minus.cube, fukui_f_zero.cube)
  - NumPy arrays for all densities and Fukui functions
  - Summary text file with energies and integrated Fukui values

No external dependencies beyond GPAW, ASE, and NumPy.
Cube I/O is self-contained (no fukui_backend import).

Usage:
    python run_fukui.py --mol H2O --ecut 500 --vacuum 12.0
    python run_fukui.py --mol pentacene --ecut 500 --vacuum 12.0
    python run_fukui.py --batch --ecut 500 --vacuum 12.0

Results: results/<mol>_PBE_<ecut>eV/
"""

import os, sys, argparse
import numpy as np

B2A = 0.529177210903  # Bohr to Angstrom

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GEOM_DIR = os.path.join(SCRIPT_DIR, 'geometries')
OUT_DIR = os.path.join(SCRIPT_DIR, 'results')

MOLECULES = ['H2O', 'CH2O', 'CH2NH', 'C2H4', 'pyrrol', 'pyridine', 'pentacene', 'PTCDA']


# ==================================================================
# Cube I/O (self-contained, no external imports)
# ==================================================================

def read_cube(fname):
    """Read a Gaussian cube file.
    Returns: data (nx,ny,nz), origin (3,), shape (nx,ny,nz),
             vecs (3x3 step vectors), atoms [(Z,x,y,z)] in Bohr."""
    with open(fname, 'r') as f:
        f.readline()  # comment 1
        f.readline()  # comment 2
        parts = f.readline().split()
        natm = int(parts[0])
        origin = np.array([float(parts[1]), float(parts[2]), float(parts[3])])
        parts = f.readline().split()
        nx = int(parts[0]); xvec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])
        parts = f.readline().split()
        ny = int(parts[0]); yvec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])
        parts = f.readline().split()
        nz = int(parts[0]); zvec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])
        atoms = []
        for _ in range(natm):
            parts = f.readline().split()
            atoms.append((int(parts[0]), float(parts[2]), float(parts[3]), float(parts[4])))
        data = np.fromfile(f, sep=' ')
    data = data.reshape(nx, ny, nz)
    return data, origin, (nx, ny, nz), (xvec, yvec, zvec), atoms


def write_cube(fname, data, origin, vecs, atoms, comment1='Cube file', comment2='Generated by run_fukui.py'):
    """Write a Gaussian cube file.
    data: (nx,ny,nz); origin: (3,) in Bohr; vecs: 3 step vectors in Bohr;
    atoms: [(Z,x,y,z)] in Bohr."""
    nx, ny, nz = data.shape
    xvec, yvec, zvec = vecs
    with open(fname, 'w') as f:
        f.write(f"{comment1}\n")
        f.write(f"{comment2}\n")
        f.write(f"{len(atoms):5d}  {origin[0]:11.6f}  {origin[1]:11.6f}  {origin[2]:11.6f}\n")
        f.write(f"{nx:5d}  {xvec[0]:11.6f}  {xvec[1]:11.6f}  {xvec[2]:11.6f}\n")
        f.write(f"{ny:5d}  {yvec[0]:11.6f}  {yvec[1]:11.6f}  {yvec[2]:11.6f}\n")
        f.write(f"{nz:5d}  {zvec[0]:11.6f}  {zvec[1]:11.6f}  {zvec[2]:11.6f}\n")
        for atom in atoms:
            Z, x, y, z = atom
            f.write(f"{Z:5d}  0.000000  {x:11.6f}  {y:11.6f}  {z:11.6f}\n")
        flat = data.ravel(order='C')
        for i in range(0, len(flat), 6):
            chunk = flat[i:i+6]
            f.write(' '.join(f'{v:13.5E}' for v in chunk) + '\n')


# ==================================================================
# Geometry helpers
# ==================================================================

def make_boxed_atoms(atoms, vacuum=10.0):
    """Center molecule in a periodic cell with vacuum padding."""
    pos = atoms.positions
    rmin = pos.min(axis=0)
    rmax = pos.max(axis=0)
    extent = rmax - rmin
    cell = extent + 2 * vacuum
    center = 0.5 * cell
    mol_center = 0.5 * (rmin + rmax)
    shift = center - mol_center
    new_atoms = atoms.copy()
    new_atoms.positions = pos + shift
    new_atoms.cell = cell
    new_atoms.pbc = [True, True, True]
    return new_atoms


def count_valence_electrons(atoms):
    """Count total electrons (neutral). GPAW default setups have all e- as valence for H,C,N,O."""
    from ase.data import atomic_numbers
    return sum(atomic_numbers[a.symbol] for a in atoms)


# ==================================================================
# GPAW calculation
# ==================================================================

def run_gpaw_sp(atoms, charge, spinpol, ecut, xc, outdir, tag, fd_width=0.05):
    """Run GPAW single-point and return (atoms, calc)."""
    from gpaw import GPAW, PW, FermiDirac
    calc = GPAW(
        mode=PW(ecut), xc=xc, charge=charge, spinpol=spinpol,
        occupations=FermiDirac(fd_width),
        kpts=(1, 1, 1),  # gamma only for isolated molecule
        symmetry='off',
        convergence={'energy': 1e-5, 'density': 1e-5, 'bands': 'occupied'},
        txt=os.path.join(outdir, f'{tag}.txt'),
    )
    a = atoms.copy()
    a.calc = calc
    E = a.get_potential_energy()
    print(f"    [{tag}] E = {E:.6f} eV  (charge={charge}, spinpol={spinpol})")
    return a, calc


def write_density_cube(atoms, calc, fname):
    """Write all-electron density cube. GPAW returns density in Å⁻³;
    cube files use Bohr grid vectors, so convert to Bohr⁻³."""
    from ase.io import write
    rho = calc.get_all_electron_density() * B2A**3  # Å⁻³ -> Bohr⁻³
    write(fname, atoms, data=rho)
    print(f"    Cube: {fname}")


# ==================================================================
# Main Fukui workflow
# ==================================================================

def compute_fukui(mol_name, ecut, vacuum, xc, outdir, geom_dir):
    """Full GPAW Fukui workflow for one molecule."""
    from ase.io import read

    os.makedirs(outdir, exist_ok=True)
    xyz_path = os.path.join(geom_dir, f'{mol_name}.xyz')
    if not os.path.isfile(xyz_path):
        print(f"ERROR: {xyz_path} not found")
        sys.exit(1)

    atoms = read(xyz_path)
    natoms = len(atoms)
    nelec = count_valence_electrons(atoms)
    boxed = make_boxed_atoms(atoms, vacuum=vacuum)

    print(f"\n{'='*60}")
    print(f"  Molecule: {mol_name}  ({natoms} atoms, {nelec} e-)")
    print(f"  Method:   GPAW {xc}  PW({ecut} eV)")
    print(f"  Vacuum:   {vacuum} A  ->  cell = {boxed.cell.diagonal()}")
    print(f"  kpts:     gamma only")
    print(f"{'='*60}")

    # Spin: even e- -> N=singlet, A/C=doublet; odd e- -> N=doublet, A/C=singlet
    neutral_even = (nelec % 2) == 0
    if neutral_even:
        spin_N, spin_A, spin_C = False, True, True
    else:
        spin_N, spin_A, spin_C = True, False, False
    print(f"  Spin: N={spin_N}, A={spin_A}, C={spin_C}")

    # Neutral (N)
    print("\n  Neutral (N)  ...")
    _, calc_N = run_gpaw_sp(boxed, charge=0, spinpol=spin_N, ecut=ecut, xc=xc, outdir=outdir, tag='N')
    write_density_cube(boxed, calc_N, os.path.join(outdir, 'rho_N.cube'))

    # Anion (N+1)
    print("  Anion (N+1) ...")
    _, calc_A = run_gpaw_sp(boxed, charge=-1, spinpol=spin_A, ecut=ecut, xc=xc, outdir=outdir, tag='A')
    write_density_cube(boxed, calc_A, os.path.join(outdir, 'rho_A.cube'))

    # Cation (N-1)
    print("  Cation (N-1) ...")
    _, calc_C = run_gpaw_sp(boxed, charge=1, spinpol=spin_C, ecut=ecut, xc=xc, outdir=outdir, tag='C')
    write_density_cube(boxed, calc_C, os.path.join(outdir, 'rho_C.cube'))

    # Compute Fukui grids from cube files
    print("\n  Computing Fukui grids ...")
    rho_N, origin, shape, vecs, atoms_cube = read_cube(os.path.join(outdir, 'rho_N.cube'))
    rho_A, _, _, _, _ = read_cube(os.path.join(outdir, 'rho_A.cube'))
    rho_C, _, _, _, _ = read_cube(os.path.join(outdir, 'rho_C.cube'))

    # Save raw densities as .npy
    np.save(os.path.join(outdir, 'rho_N.npy'), rho_N)
    np.save(os.path.join(outdir, 'rho_A.npy'), rho_A)
    np.save(os.path.join(outdir, 'rho_C.npy'), rho_C)

    f_plus  = rho_A - rho_N   # electrophilic Fukui (where electron goes)
    f_minus = rho_N - rho_C   # nucleophilic Fukui (where electron leaves)
    f_zero  = 0.5 * (f_plus + f_minus)

    for tname, grid in [('fukui_f_plus', f_plus), ('fukui_f_minus', f_minus), ('fukui_f_zero', f_zero)]:
        np.save(os.path.join(outdir, f'{tname}.npy'), grid)
        write_cube(os.path.join(outdir, f'{tname}.cube'), grid, origin, vecs, atoms_cube,
                   comment1=f'{mol_name} Fukui {tname}', comment2=f'GPAW {xc} PW({ecut}eV)')
        print(f"    {tname}: range [{grid.min():.3e}, {grid.max():.3e}]")

    # Integrated totals (sanity: f+ ~ +1, f- ~ +1)
    dx, dy, dz = vecs[0][0], vecs[1][1], vecs[2][2]
    dV = abs(dx * dy * dz)
    int_fp = np.sum(f_plus)  * dV
    int_fm = np.sum(f_minus) * dV
    int_f0 = np.sum(f_zero)  * dV
    print(f"\n  Integrated f+: {int_fp:.4f} e  (expect ~+1)")
    print(f"  Integrated f-: {int_fm:.4f} e  (expect ~+1)")
    print(f"  Integrated f0: {int_f0:.4f} e  (expect ~+1)")

    # Summary
    with open(os.path.join(outdir, 'summary.txt'), 'w') as f:
        f.write(f"Molecule: {mol_name}\n")
        f.write(f"Method: GPAW {xc} PW({ecut} eV)\n")
        f.write(f"Vacuum: {vacuum} A, cell = {boxed.cell.diagonal()}\n")
        f.write(f"Atoms: {natoms}, Electrons: {nelec}\n")
        f.write(f"Integrated f+: {int_fp:.6f}\n")
        f.write(f"Integrated f-: {int_fm:.6f}\n")
        f.write(f"Integrated f0: {int_f0:.6f}\n")

    print(f"\n  Results: {outdir}")
    return outdir


def main():
    parser = argparse.ArgumentParser(description='GPAW Fukui functions for isolated molecules (self-contained)')
    parser.add_argument('--mol', type=str, default=None, help='Molecule name (e.g. H2O, pentacene)')
    parser.add_argument('--batch', action='store_true', help='Run all molecules')
    parser.add_argument('--ecut', type=float, default=500.0, help='Plane-wave cutoff in eV (default: 500)')
    parser.add_argument('--vacuum', type=float, default=12.0, help='Vacuum padding in Angstrom (default: 12)')
    parser.add_argument('--xc', type=str, default='PBE', help='XC functional (default: PBE)')
    parser.add_argument('--outdir', type=str, default=OUT_DIR, help='Output root directory')
    parser.add_argument('--geom-dir', type=str, default=GEOM_DIR, help='Directory containing .xyz files')
    args = parser.parse_args()

    if args.batch:
        mols = MOLECULES
    elif args.mol:
        mols = [args.mol]
    else:
        parser.error('Specify --mol <name> or --batch')

    for mol in mols:
        tag = f"{mol}_{args.xc}_{int(args.ecut)}eV"
        resdir = os.path.join(args.outdir, tag)
        compute_fukui(mol, ecut=args.ecut, vacuum=args.vacuum, xc=args.xc, outdir=resdir, geom_dir=args.geom_dir)

    print(f"\n{'='*60}")
    print(f"  All done. Results in: {args.outdir}")
    print(f"{'='*60}")


if __name__ == '__main__':
    main()
