#!/usr/bin/env python3
"""Backend module for Fukui function computation.

Separates compute algorithms from plotting/diagnostics per AGENTS.md Rule 3.
No plotting code here; thin CLI wrappers call these functions and handle I/O.
"""

import os
import numpy as np
from pyscf import gto, dft
from pyscf.tools import cubegen

B2A = 0.529177210903  # Bohr to Angstrom


def read_xyz(fname):
    """Read an XYZ file and return a pyscf geometry string.
    Ignores any charge column if present."""
    with open(fname, 'r') as f:
        lines = f.readlines()
    natm = int(lines[0].strip())
    atoms = []
    for i in range(2, 2 + natm):
        parts = lines[i].split()
        symbol = parts[0]
        x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
        atoms.append(f'{symbol} {x} {y} {z}')
    return '; '.join(atoms)


def run_sp(mol_geom, basis, xc_func, charge, spin):
    """Run a single-point DFT calculation at fixed geometry.

    Parameters
    ----------
    mol_geom : str
        PySCF geometry string (e.g. 'H 0 0 0; C 0 0 1') in Angstrom.
    basis : str
        Basis set name.
    xc_func : str
        XC functional name.
    charge : int
        Molecular charge.
    spin : int
        Spin multiplicity (0 for singlet, 1 for doublet, ...).

    Returns
    -------
    mol, mf : (Mole, RKS/UKS)
    """
    mol = gto.Mole(atom=mol_geom, basis=basis, charge=charge, spin=spin, unit='Angstrom')
    mol.build()
    mf = dft.RKS(mol) if spin == 0 else dft.UKS(mol)
    mf.xc = xc_func
    mf.kernel()
    return mol, mf


def write_density_cube(mol, mf, fname, resolution=0.15, margin=4.0):
    """Write total electron density cube file.

    Handles both RKS (2D DM) and UKS (3D DM) correctly by summing alpha+beta.
    """
    dm = mf.make_rdm1()
    if dm.ndim == 3:
        dm = dm[0] + dm[1]
    cubegen.density(mol, fname, dm, resolution=resolution, margin=margin)


def mulliken_charges(mol, mf):
    """Return Mulliken atomic charges without printing."""
    dm = mf.make_rdm1()
    if dm.ndim == 3:
        dm = dm[0] + dm[1]
    s = mol.intor('int1e_ovlp')
    diag = np.diag(np.dot(dm, s))
    chg = np.empty(mol.natm)
    for ia in range(mol.natm):
        ao0, ao1 = mol.aoslice_by_atom()[ia][2:]
        pop = np.sum(diag[ao0:ao1])
        chg[ia] = mol.atom_charge(ia) - pop
    return chg


def read_cube(fname):
    """Read a Gaussian cube file.

    Returns
    -------
    data : ndarray (nx, ny, nz)
    origin : ndarray (3,)
    shape : tuple (nx, ny, nz)
    vecs : tuple of 3 ndarrays — grid step vectors
    atoms : list of (Z, x, y, z)
    """
    with open(fname, 'r') as f:
        f.readline()
        f.readline()
        parts = f.readline().split()
        natm = int(parts[0])
        origin = np.array([float(parts[1]), float(parts[2]), float(parts[3])])

        parts = f.readline().split()
        nx = int(parts[0])
        xvec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])

        parts = f.readline().split()
        ny = int(parts[0])
        yvec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])

        parts = f.readline().split()
        nz = int(parts[0])
        zvec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])

        atoms = []
        for _ in range(natm):
            parts = f.readline().split()
            atoms.append((int(parts[0]), float(parts[2]), float(parts[3]), float(parts[4])))

        data = np.fromfile(f, sep=' ')
    data = data.reshape(nx, ny, nz)
    return data, origin, (nx, ny, nz), (xvec, yvec, zvec), atoms


def write_cube(fname, data, origin, vecs, atoms, comment1='Cube file', comment2='Generated by fukui_backend'):
    """Write a Gaussian cube file.

    Parameters
    ----------
    fname : str
        Output file path.
    data : ndarray (nx, ny, nz)
        3D scalar field.
    origin : ndarray (3,)
        Grid origin in Bohr.
    vecs : tuple of 3 ndarrays
        Grid step vectors in Bohr.
    atoms : list of (Z, x, y, z)
        Atomic numbers and positions in Bohr.
    comment1, comment2 : str
        Header comment lines.
    """
    nx, ny, nz = data.shape
    xvec, yvec, zvec = vecs
    with open(fname, 'w') as f:
        f.write(f"{comment1}\n")
        f.write(f"{comment2}\n")
        f.write(f"{len(atoms):5d}  {origin[0]:11.6f}  {origin[1]:11.6f}  {origin[2]:11.6f}\n")
        f.write(f"{nx:5d}  {xvec[0]:11.6f}  {xvec[1]:11.6f}  {xvec[2]:11.6f}\n")
        f.write(f"{ny:5d}  {yvec[0]:11.6f}  {yvec[1]:11.6f}  {yvec[2]:11.6f}\n")
        f.write(f"{nz:5d}  {zvec[0]:11.6f}  {zvec[1]:11.6f}  {zvec[2]:11.6f}\n")
        for atom in atoms:
            Z, x, y, z = atom
            f.write(f"{Z:5d}  0.000000  {x:11.6f}  {y:11.6f}  {z:11.6f}\n")
        flat = data.ravel(order='C')
        nvals = len(flat)
        for i in range(0, nvals, 6):
            chunk = flat[i:i + 6]
            line = ' '.join(f'{v:13.5E}' for v in chunk)
            f.write(line + '\n')


def compute_fukui_mulliken(mol_N, mf_N, mol_A, mf_A, mol_C, mf_C):
    """Compute condensed Mulliken Fukui indices.

    Returns
    -------
    labels : list of element symbols
    fA_plus, fA_minus, fA_0 : ndarray (natoms,)
    """
    q_N = mulliken_charges(mol_N, mf_N)
    q_A = mulliken_charges(mol_A, mf_A)
    q_C = mulliken_charges(mol_C, mf_C)

    fA_plus = q_N - q_A
    fA_minus = q_C - q_N
    fA_0 = 0.5 * (fA_plus + fA_minus)

    labels = [mol_N.atom_symbol(i) for i in range(mol_N.natm)]
    return labels, fA_plus, fA_minus, fA_0


def write_mulliken_table(fname, labels, fA_plus, fA_minus, fA_0):
    """Write condensed Fukui indices to a text file."""
    with open(fname, 'w') as f:
        f.write("Atom       f+          f-          f0\n")
        for i, lab in enumerate(labels):
            f.write(f"{lab:>4}  {fA_plus[i]:10.6f}  {fA_minus[i]:10.6f}  {fA_0[i]:10.6f}\n")


def run_fukui_for_molecule(name, geom_str, outdir, basis='def2-svp', xc_func='b3lyp',
                           resolution=0.15, margin=4.0):
    """Full Fukui workflow for a single molecule.

    Parameters
    ----------
    name : str
        Molecule label (used for directory naming).
    geom_str : str
        PySCF geometry string in Angstrom.
    outdir : str
        Parent output directory; a sub-directory ``name/`` is created.
    basis, xc_func : str
        DFT settings.
    resolution, margin : float
        Cube grid parameters.

    Returns
    -------
    resdir : str
        Path to the created results directory.
    """
    resdir = os.path.join(outdir, name)
    os.makedirs(resdir, exist_ok=True)

    print(f"\n{'='*50}")
    print(f"  Molecule: {name}")
    print(f"{'='*50}")

    # ---- Run SCF for N, N+1, N-1 ---------------------------------------
    print("  Neutral  (N)  ...")
    mol_N, mf_N = run_sp(geom_str, basis, xc_func, charge=0, spin=0)
    print(f"    E_N  = {mf_N.e_tot:.6f} Ha")

    print("  Anion    (N+1) ...")
    mol_A, mf_A = run_sp(geom_str, basis, xc_func, charge=-1, spin=1)
    print(f"    E_A  = {mf_A.e_tot:.6f} Ha")

    print("  Cation   (N-1) ...")
    mol_C, mf_C = run_sp(geom_str, basis, xc_func, charge=1, spin=1)
    print(f"    E_C  = {mf_C.e_tot:.6f} Ha")

    # ---- Write cube files ----------------------------------------------
    cube_N = os.path.join(resdir, 'rho_N.cube')
    cube_A = os.path.join(resdir, 'rho_A.cube')
    cube_C = os.path.join(resdir, 'rho_C.cube')

    print("  Writing cube files ...")
    write_density_cube(mol_N, mf_N, cube_N, resolution, margin)
    write_density_cube(mol_A, mf_A, cube_A, resolution, margin)
    write_density_cube(mol_C, mf_C, cube_C, resolution, margin)

    # ---- Save .npy copies ----------------------------------------------
    rho_N, _, _, _, _ = read_cube(cube_N)
    rho_A, _, _, _, _ = read_cube(cube_A)
    rho_C, _, _, _, _ = read_cube(cube_C)
    np.save(os.path.join(resdir, 'rho_N.npy'), rho_N)
    np.save(os.path.join(resdir, 'rho_A.npy'), rho_A)
    np.save(os.path.join(resdir, 'rho_C.npy'), rho_C)

    # ---- Condensed Mulliken indices ------------------------------------
    labels, fA_plus, fA_minus, fA_0 = compute_fukui_mulliken(mol_N, mf_N, mol_A, mf_A, mol_C, mf_C)
    write_mulliken_table(os.path.join(resdir, 'mulliken_fukui.txt'), labels, fA_plus, fA_minus, fA_0)

    print("  Condensed Mulliken Fukui indices:")
    print(f"  {'Atom':>4}  {'f+':>10}  {'f-':>10}  {'f0':>10}")
    for i, lab in enumerate(labels):
        print(f"  {lab:>4}  {fA_plus[i]:10.6f}  {fA_minus[i]:10.6f}  {fA_0[i]:10.6f}")

    print(f"  Results saved to: {resdir}")
    return resdir
