#!/usr/bin/env python3
"""Compute Fukui function cube files from neutral, anion, and cation density cubes.

f+ = rho(anion) - rho(neutral)
f- = rho(neutral) - rho(cation)
f0 = 0.5 * (f+ + f-)
"""

import argparse
import os
import sys

fukui_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, fukui_dir)
from fukui_backend import read_cube, write_cube


def make_fukui_cubes(cube_N, cube_A, cube_C, outdir):
    rho_N, origin, shape, vecs, atoms = read_cube(cube_N)
    rho_A, _, _, _, _ = read_cube(cube_A)
    rho_C, _, _, _, _ = read_cube(cube_C)

    f_plus = rho_A - rho_N
    f_minus = rho_N - rho_C
    f_dual = 0.5 * (f_plus + f_minus)

    os.makedirs(outdir, exist_ok=True)

    out_plus = os.path.join(outdir, 'fukui_plus.cube')
    out_minus = os.path.join(outdir, 'fukui_minus.cube')
    out_dual = os.path.join(outdir, 'fukui_dual.cube')

    write_cube(out_plus, f_plus, origin, vecs, atoms,   comment1='Fukui f+ = rho(N+1) - rho(N)', comment2='Generated by make_fukui_cubes.py')
    write_cube(out_minus, f_minus, origin, vecs, atoms, comment1='Fukui f- = rho(N) - rho(N-1)', comment2='Generated by make_fukui_cubes.py')
    write_cube(out_dual, f_dual, origin, vecs, atoms,   comment1='Fukui f0 = 0.5 * (f+ + f-)',   comment2='Generated by make_fukui_cubes.py')

    print(f"Wrote {out_plus}")
    print(f"Wrote {out_minus}")
    print(f"Wrote {out_dual}")


def main():
    parser = argparse.ArgumentParser(description='Make Fukui function cube files from density cubes.')
    parser.add_argument('--cube-N', required=True, help='Neutral density cube')
    parser.add_argument('--cube-A', required=True, help='Anion density cube (N+1)')
    parser.add_argument('--cube-C', required=True, help='Cation density cube (N-1)')
    parser.add_argument('--outdir', required=True, help='Output directory')
    args = parser.parse_args()

    make_fukui_cubes(args.cube_N, args.cube_A, args.cube_C, args.outdir)


if __name__ == '__main__':
    main()
