#!/usr/bin/env python3
"""generate_fukui_slab_jobs.py — bake GPAW Fukui function scripts + PBS for relaxed metal slabs.

Reads relaxed slab geometries from jobs_coinage/results_{Metal}_{variant}_111_3x3x3/relaxed.xyz
and bakes standalone runner scripts that compute Fukui functions (f+, f-, f0) via 3 SCF
calculations at charge = 0, -1, +1.

Variants: bare, adatom, dimer, trimer, row
Metals: Cu, Ag, Au
Total: 3 × 5 = 15 jobs

Each job:
  - Loads relaxed slab geometry (relaxed.xyz)
  - Runs 3 SCF: neutral (charge=0), anion (charge=-1), cation (charge=+1)
  - Writes all-electron density cubes for each
  - Computes f+ = rho(N+1) - rho(N), f- = rho(N) - rho(N-1), f0 = 0.5*(f+ + f-)
  - Saves Fukui cubes + npy + energy summary + ChemBook metadata

Usage:
    python generate_fukui_slab_jobs.py
    python generate_fukui_slab_jobs.py --metals Cu --variants bare adatom
    python generate_fukui_slab_jobs.py --outdir jobs_fukui_slab
"""
import os, sys, json, argparse, secrets
import numpy as np
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if REPO not in sys.path:
    sys.path.insert(0, REPO)

BASE = os.path.dirname(os.path.abspath(__file__))
RELAXED_DIR = os.path.join(BASE, 'jobs_coinage')

METALS = ['Cu', 'Ag', 'Au']
VARIANTS = ['bare', 'adatom', 'dimer', 'trimer', 'row']

PBS_RESOURCES = {
    'ncpus': 8, 'mem': '32gb', 'walltime': '23:00:00', 'scratch_gb': 20,
}

def read_relaxed_xyz(path):
    """Read extended XYZ (ASE format) without ASE dependency."""
    with open(path) as f:
        lines = f.readlines()
    n = int(lines[0].strip())
    header = lines[1]
    # Parse Lattice from header
    import re
    lat_match = re.search(r'Lattice="([^"]+)"', header)
    cell = np.array([float(x) for x in lat_match.group(1).split()]).reshape(3, 3)
    syms = []; ps = []
    for i in range(n):
        parts = lines[2 + i].split()
        syms.append(parts[0])
        ps.append([float(parts[1]), float(parts[2]), float(parts[3])])
    return syms, np.array(ps), cell

def bake_run_script(metal, variant, syms, ps, cell, outdir, ecut=400.0, xc='PBE'):
    job_name = f"{metal}_{variant}_111_3x3x3"
    results_dir = f"results_{job_name}_fukui"
    n_atoms = len(syms)
    elem_counts = Counter(syms)

    # Determine spin: for metals with FermiDirac smearing, use spinpol=False for all
    # The smearing handles fractional occupation at Fermi level
    spin_N = "False"
    spin_A = "False"
    spin_C = "False"

    sym_list = repr(syms)
    pos_list = repr(ps.tolist())
    cell_list = repr(cell.tolist())

    script = f'''#!/usr/bin/env python3
"""Fukui functions for {metal} {variant} FCC(111) 3x3x3 slab — GPAW PBE PW({int(ecut)}eV)
Auto-generated by generate_fukui_slab_jobs.py. 3 SCF calculations (N, N+1, N-1) + Fukui grids.
"""
import os, sys, json, time, socket, atexit
import numpy as np
from datetime import datetime, timezone

os.environ.setdefault('GPAW_SETUP_PATH', '/storage/praha1/home/prokop/gpaw-setups-24.1.0/gpaw-setups-24.1.0')

from ase import Atoms
from ase.io import write
from gpaw import GPAW, PW, FermiDirac

METAL = "{metal}"; VARIANT = "{variant}"; JOB_NAME = "{job_name}"
ECUT = {ecut}; XC = "{xc}"; KPTS = (1, 1, 1); SMEARING = 0.05
N_ATOMS = {n_atoms}

OUTDIR = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(OUTDIR, "{results_dir}")
os.makedirs(RESULTS, exist_ok=True)

# --- ChemBook provenance ---
_cb_path = os.path.join(RESULTS, 'chembook.json')
_cb_node = {{
    "chembook": {{"schema": "chembook.job.v0", "id": "{secrets.token_hex(6)}", "created": datetime.now(timezone.utc).isoformat(timespec='microseconds'), "status": "pending"}},
    "job": {{"type": "fukui", "name": JOB_NAME}},
    "system": {{"n_atoms": N_ATOMS, "elements": {dict(elem_counts)}, "metal": METAL, "variant": VARIANT, "surface": "FCC(111)", "supercell": [3,3,3]}},
    "method": {{"code": "gpaw", "basis": "PW({int(ecut)}eV)", "method": XC, "kpts": list(KPTS), "smearing": SMEARING, "dipole": "z", "spinpol": False}},
    "provenance": {{"command": " ".join(sys.argv), "hostname": socket.gethostname(), "cwd": os.path.dirname(os.path.abspath(__file__))}},
}}
with open(_cb_path, 'w') as _cb_f:
    json.dump(_cb_node, _cb_f, indent=2)
_cb_t0 = time.perf_counter_ns()

def _cb_on_exit():
    if _cb_node["chembook"]["status"] == "pending":
        _cb_dur = (time.perf_counter_ns() - _cb_t0) / 1e9
        _cb_node["chembook"]["status"] = "failed"
        _cb_node["provenance"]["duration_sec"] = _cb_dur
        _cb_node["provenance"]["exit_code"] = 1
        with open(_cb_path, 'w') as _cb_f:
            json.dump(_cb_node, _cb_f, indent=2)
atexit.register(_cb_on_exit)

# --- Build atoms ---
atoms = Atoms(symbols={sym_list}, positions={pos_list}, cell={cell_list}, pbc=[True, True, False])

# --- Helper: run SCF and write density cube ---
def run_scf(charge, tag):
    calc = GPAW(
        mode=PW(ECUT), xc=XC, kpts=KPTS, spinpol=False, charge=charge,
        symmetry='off', maxiter=333,
        occupations=FermiDirac(SMEARING),
        convergence=dict(energy=1e-5, density=1e-5, bands='occupied'),
        poissonsolver={{'dipolelayer': 'xy'}},
        txt=os.path.join(RESULTS, f'{{tag}}.txt'),
    )
    a = atoms.copy()
    a.calc = calc
    E = a.get_potential_energy()
    print(f"  [{{tag}}] E = {{E:.6f}} eV  (charge={{charge}})")
    rho = calc.get_all_electron_density()
    write(os.path.join(RESULTS, f'rho_{{tag}}.cube'), a, data=rho)
    np.save(os.path.join(RESULTS, f'rho_{{tag}}.npy'), rho)
    return E, rho

# --- Run 3 SCF calculations ---
print(f"[{{JOB_NAME}}] Fukui: {{N_ATOMS}} atoms, ecut={{ECUT}}eV, kpts={{KPTS}}")
t0 = time.time()

print("  Neutral (N) ...")
E_N, rho_N = run_scf(0, 'N')

print("  Anion (N+1) ...")
E_A, rho_A = run_scf(-1, 'A')

print("  Cation (N-1) ...")
E_C, rho_C = run_scf(1, 'C')

# --- Compute Fukui grids ---
f_plus  = rho_A - rho_N
f_minus = rho_N - rho_C
f_zero  = 0.5 * (f_plus + f_minus)

for tname, grid in [('fukui_f_plus', f_plus), ('fukui_f_minus', f_minus), ('fukui_f_zero', f_zero)]:
    np.save(os.path.join(RESULTS, f'{{tname}}.npy'), grid)
    print(f"  {{tname}}: range [{{grid.min():.3e}}, {{grid.max():.3e}}]")

# --- Energy summary ---
t1 = time.time()
elapsed = t1 - t0
print(f"[{{JOB_NAME}}] Done in {{elapsed:.1f}}s")
print(f"  E_N={{E_N:.6f}}, E_A={{E_A:.6f}}, E_C={{E_C:.6f}}")
print(f"  EA={{E_A - E_N:.6f}} eV, IP={{E_N - E_C:.6f}} eV")

# --- ChemBook done ---
_cb_dur = (time.perf_counter_ns() - _cb_t0) / 1e9
_cb_node["chembook"]["status"] = "done"
_cb_node["provenance"]["duration_sec"] = _cb_dur
_cb_node["provenance"]["exit_code"] = 0
_cb_node["results"] = {{
    "E_N_eV": float(E_N), "E_A_eV": float(E_A), "E_C_eV": float(E_C),
    "EA_eV": float(E_A - E_N), "IP_eV": float(E_N - E_C),
    "elapsed_s": elapsed,
}}
with open(_cb_path, 'w') as _cb_f:
    json.dump(_cb_node, _cb_f, indent=2)
print(f"[{{JOB_NAME}}] chembook.json written.")
'''
    path = os.path.join(outdir, f'run_fukui_{metal}_{variant}.py')
    with open(path, 'w') as f:
        f.write(script)
    return path

def bake_pbs_script(metal, variant, outdir):
    job_name = f"fukui_{metal}_{variant}"
    r = PBS_RESOURCES
    script = f'''#!/bin/bash
#PBS -N {job_name}
#PBS -l select=1:ncpus={r['ncpus']}:mem={r['mem']}:scratch_local={r['scratch_gb']}gb
#PBS -l walltime={r['walltime']}
#PBS -j oe
#PBS -q luna
#PBS -m bae

trap 'cp -r $SCRATCHDIR/* $PBS_O_WORKDIR/ 2>/dev/null; rm -rf $SCRATCHDIR/* 2>/dev/null' EXIT

cd $PBS_O_WORKDIR
module purge
module add py-gpaw/24.1.0-gcc-10.2.1-fojjhkw
export GPAW_SETUP_PATH=/storage/praha1/home/prokop/gpaw-setups-24.1.0/gpaw-setups-24.1.0
export OMP_NUM_THREADS=1
export PYTHONUNBUFFERED=1

echo "=== {job_name} === $(date)"
echo "Node: $(hostname)"

cp $PBS_O_WORKDIR/run_fukui_{metal}_{variant}.py $SCRATCHDIR/
cd $SCRATCHDIR
export TMPDIR=$SCRATCHDIR

mpirun -np $PBS_NUM_PPN python3 run_fukui_{metal}_{variant}.py 2>&1

echo "Finished: $(date)"
cp -r $SCRATCHDIR/results_* $PBS_O_WORKDIR/ 2>/dev/null
'''
    path = os.path.join(outdir, f'submit_fukui_{metal}_{variant}.pbs')
    with open(path, 'w') as f:
        f.write(script)
    return path

def main():
    parser = argparse.ArgumentParser(description="Bake GPAW Fukui jobs for relaxed metal slabs")
    parser.add_argument('--metals', nargs='+', default=METALS)
    parser.add_argument('--variants', nargs='+', default=VARIANTS)
    parser.add_argument('--outdir', default=os.path.join(BASE, 'jobs_fukui_slab'))
    parser.add_argument('--ecut', type=float, default=400.0)
    parser.add_argument('--xc', default='PBE')
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    n_baked = 0

    for metal in args.metals:
        for variant in args.variants:
            relaxed_xyz = os.path.join(RELAXED_DIR, f'results_{metal}_{variant}_111_3x3x3', 'relaxed.xyz')
            if not os.path.exists(relaxed_xyz):
                print(f"SKIP {metal}/{variant}: no relaxed geometry at {relaxed_xyz}")
                continue

            syms, ps, cell = read_relaxed_xyz(relaxed_xyz)
            run_path = bake_run_script(metal, variant, syms, ps, cell, args.outdir, ecut=args.ecut, xc=args.xc)
            pbs_path = bake_pbs_script(metal, variant, args.outdir)
            print(f"  {metal}/{variant}: {len(syms)} atoms → {run_path}, {pbs_path}")
            n_baked += 1

    # Generate submit_all.sh
    submit_path = os.path.join(args.outdir, 'submit_all.sh')
    with open(submit_path, 'w') as f:
        f.write("#!/bin/bash\n# Submit all Fukui slab jobs\n")
        for metal in args.metals:
            for variant in args.variants:
                pbs = f'submit_fukui_{metal}_{variant}.pbs'
                if os.path.exists(os.path.join(args.outdir, pbs)):
                    f.write(f"qsub {pbs}\n")
    os.chmod(submit_path, 0o755)
    print(f"\nBaked {n_baked} jobs → {args.outdir}/")
    print(f"Submit: cd {args.outdir} && bash submit_all.sh")

if __name__ == '__main__':
    main()
